name: CI Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_SECRET_KEY }}

          port: 22
          script: |
            cd /var/www/tsdroq
            git pull origin main
            echo "Installing dependencies..."
            php artisan storage:link
            composer install --no-scripts --no-progress --prefer-dist
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize
            php artisan migrate --force
            npm install
            npm run build
            echo "Deployment complete."
